version: '3.1'

services:
  map:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mglFuture7@$
      MYSQL_DATABASE: mgldefi
      MYSQL_USER: main
      MYSQL_PASSWORD: mglFuture7@$
      MYSQL_INITDB_SKIP_TZINFO: 'true'
      MYSQL_INITDB_SKIP_TEST_DB: 'true'
      MYSQL_DATABASE_CHARSET: utf8mb4
      MYSQL_DATABASE_COLLATE: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - db_data1:/var/lib/mysql
      - ./backend/src/db/new_mgldefi.sql:/docker-entrypoint-initdb.d/mgldefi.sql
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  db_data1:
